// Generates TypeScript outputs from the JSON Schemas in ../schemas:
//   gen/ts/types.ts    - interfaces (via json-schema-to-typescript)
//   gen/ts/schemas.ts  - the schemas as runtime consts (for Ajv validation)
// Then best-effort generates the Python models (non-fatal if no Python toolchain).
//
// Run with:  pnpm --filter @fpg/schemas codegen   (or root `pnpm codegen`)

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { spawnSync } from 'node:child_process';
import { compile } from 'json-schema-to-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, '..');
const schemasDir = join(pkgRoot, 'schemas');
const outDir = join(pkgRoot, 'gen', 'ts');
mkdirSync(outDir, { recursive: true });

const BANNER = '// AUTO-GENERATED by packages/schemas/scripts/codegen.mjs — DO NOT EDIT.\n';

// The root entity schemas (each has a top-level `schema_version`).
const ROOT_ENTITIES = {
  Project: 'project.schema.json',
  Boundary: 'boundary.schema.json',
  ProgramGraph: 'program-graph.schema.json',
  Plan: 'plan.schema.json',
  RuleSet: 'ruleset.schema.json',
  ValidationReport: 'validation-report.schema.json',
};

const schemaFiles = readdirSync(schemasDir).filter((f) => f.endsWith('.schema.json'));
const schemasById = {};
for (const file of schemaFiles) {
  schemasById[file] = JSON.parse(readFileSync(join(schemasDir, file), 'utf8'));
}

// 1) gen/ts/schemas.ts — runtime consts keyed by $id.
function writeSchemaConsts() {
  const ids = Object.keys(schemasById).sort();
  let out = BANNER;
  out += 'export const schemas: Record<string, Record<string, unknown>> = ';
  const obj = {};
  for (const id of ids) obj[id] = schemasById[id];
  out += JSON.stringify(obj, null, 2) + ';\n\n';
  out += 'export const schemaIds = ' + JSON.stringify(ids) + ' as const;\n';
  out += 'export type SchemaId = (typeof schemaIds)[number];\n\n';
  out += 'export const rootEntities = ' + JSON.stringify(ROOT_ENTITIES, null, 2) + ' as const;\n';
  writeFileSync(join(outDir, 'schemas.ts'), out);
}

// 2) gen/ts/types.ts — interfaces via json-schema-to-typescript.
async function writeTypes() {
  const root = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: pathToFileURL(join(schemasDir, '_root.schema.json')).href,
    title: 'FpgSchemas',
    type: 'object',
    additionalProperties: false,
    required: Object.keys(ROOT_ENTITIES),
    properties: Object.fromEntries(
      Object.entries(ROOT_ENTITIES).map(([name, file]) => [name, { $ref: file }]),
    ),
  };
  const ts = await compile(root, 'FpgSchemas', {
    cwd: schemasDir + '/',
    additionalProperties: false,
    declareExternallyReferenced: true,
    bannerComment: BANNER.trim(),
    style: { singleQuote: true, semi: true, trailingComma: 'all', printWidth: 100 },
  });
  writeFileSync(join(outDir, 'types.ts'), ts);
}

// 3) Python models — best effort.
function writePython() {
  const r = spawnSync(process.execPath, [join(here, 'codegen-python.mjs')], { stdio: 'inherit' });
  if (r.status !== 0) {
    console.warn(
      '\n[codegen] Python models were NOT generated (no Python/uv/Docker found). ' +
        'TypeScript outputs are complete. Run `pnpm --filter @fpg/schemas codegen:py` ' +
        'once a Python toolchain or Docker is available.\n',
    );
  }
}

await writeTypes();
writeSchemaConsts();
if (!process.env.FPG_SKIP_PY) writePython();
console.log('[codegen] wrote gen/ts/types.ts and gen/ts/schemas.ts');
